<a href="https://colab.research.google.com/github/Deeva2601/Retail_Sales_Analysis/blob/main/Superstore_Cleaned.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"/content/Raw_Superstore_Data.csv")
df.head(5)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,NaN,NaN,0.3
1,CA-2017-129684,Claire Gute,Consumer,South,NaN,Office Supplies,Apple iPhone 7,240.59,6.0,0.0
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,NaN,Staples Notebook,676.50,5.0,0.0
3,CA-2018-122872,Sara Parker,NaN,East,Washington,NaN,Hon Deluxe Fabric Chair,NaN,7.0,0.1
4,CA-2018-185789,Sara Parker,NaN,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.0,0.3

In [3]:
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          255 non-null    object
 1   Customer Name     234 non-null    object
 2   Segment           187 non-null    object
 3   Region            196 non-null    object
 4   City              218 non-null    object
 5   Product Category  187 non-null    object
 6   Product Name      223 non-null    object
 7   Sales             223 non-null    float64
 8   Quantity          234 non-null    float64
 9   Discount          201 non-null    float64
dtypes: float64(3), object(7)
memory usage: 20.1+ KB

            Sales    Quantity    Discount
count  223.000000  234.000000  201.000000
mean   505.741300    5.709402    0.220896
std    296.766739    2.964916    0.178497
min     14.220000    1.000000    0.000000
25%    240.455000    3.000000    0.100000
50%    511.560000    6.000000    0.200000
75%    764.085000    8.000000    0.300000
max    999.280000   10.000000    0.500000

In [4]:
df.isnull().sum()

Order ID             0
Customer Name       21
Segment             68
Region              59
City                37
Product Category    68
Product Name        32
Sales               32
Quantity            21
Discount            54
dtype: int64

## Remove the NULL value in Sales,Quantity and discount because in numeric data we use mean ,median

In [5]:
df['Sales'].fillna(df['Sales'].median(),inplace = True)
df['Quantity'].fillna(df['Quantity'].mean(),inplace = True)
df['Discount'].fillna(df['Discount'].mean(),inplace = True)

/tmp/ipykernel_16735/190605659.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].median(),inplace = True)
/tmp/ipykernel_16735/190605659.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(),inplace = True)
/tmp/ipykernel_16735/190605659.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].fillna(df['Discount'].mean(),inplace = True)

In [6]:
df.head(7)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.3
1,CA-2017-129684,Claire Gute,Consumer,South,NaN,Office Supplies,Apple iPhone 7,240.59,6.000000,0.0
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,NaN,Staples Notebook,676.50,5.000000,0.0
3,CA-2018-122872,Sara Parker,NaN,East,Washington,NaN,Hon Deluxe Fabric Chair,511.56,7.000000,0.1
4,CA-2018-185789,Sara Parker,NaN,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.3
5,CA-2014-116775,John Lee,Corporate,Central,Seattle,Technology,NaN,511.56,5.709402,0.5
6,CA-2016-120470,Laila Wilson,Consumer,South,Washington,Technology,Bush Somerset Collection,746.15,8.000000,0.5

In [7]:
df['Segment'].fillna(df['Segment'].mode())

0         Consumer
1         Consumer
2         Consumer
3              NaN
4              NaN
          ...
250    Home Office
251            NaN
252       Consumer
253            NaN
254            NaN
Name: Segment, Length: 255, dtype: object

In [8]:
df.isnull().sum()

Order ID             0
Customer Name       21
Segment             68
Region              59
City                37
Product Category    68
Product Name        32
Sales                0
Quantity             0
Discount             0
dtype: int64

# we remove the all category nulls using mode

In [9]:
categorial_cols = ['Customer Name','Segment','Region','City','Product Category','Product Name']
for cols in categorial_cols:
  df[cols].fillna(df[cols].mode()[0],inplace = True)

/tmp/ipykernel_16735/3890634802.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(df[cols].mode()[0],inplace = True)

In [10]:
categorical_null_counts = df[categorial_cols].isnull().sum()

In [11]:
df.isnull().sum()

Order ID            0
Customer Name       0
Segment             0
Region              0
City                0
Product Category    0
Product Name        0
Sales               0
Quantity            0
Discount            0
dtype: int64

## Next Step: Remove Duplicates

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.isnull().sum()

Order ID            0
Customer Name       0
Segment             0
Region              0
City                0
Product Category    0
Product Name        0
Sales               0
Quantity            0
Discount            0
dtype: int64

In [23]:
df.to_csv("cleaned_dataset.csv")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 245 entries, 0 to 244
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          245 non-null    object
 1   Customer Name     245 non-null    object
 2   Segment           245 non-null    object
 3   Region            245 non-null    object
 4   City              245 non-null    object
 5   Product Category  245 non-null    object
 6   Product Name      245 non-null    object
 7   Sales             245 non-null    float64
 8   Quantity          245 non-null    float64
 9   Discount          245 non-null    float64
dtypes: float64(3), object(7)
memory usage: 21.1+ KB

# we add dummy date column for future analysis

In [31]:
import pandas as pd
# assume df me abhi 'Month' aur 'Year' columns hain
df['Date'] = pd.to_datetime(df['Year'].astype(str) + '-' + df['Month'].astype(str) + '-01')

In [33]:
df.head(7)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount,Month,Year,Date
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.3,1,2020,2020-01-01
1,CA-2017-129684,Claire Gute,Consumer,South,Seattle,Office Supplies,Apple iPhone 7,240.59,6.000000,0.0,2,2020,2020-02-01
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,Technology,Staples Notebook,676.50,5.000000,0.0,3,2020,2020-03-01
3,CA-2018-122872,Sara Parker,Home Office,East,Washington,Technology,Hon Deluxe Fabric Chair,511.56,7.000000,0.1,4,2020,2020-04-01
4,CA-2018-185789,Sara Parker,Home Office,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.3,5,2020,2020-05-01
5,CA-2014-116775,John Lee,Corporate,Central,Seattle,Technology,Fellowes Banks Janalo,511.56,5.709402,0.5,6,2020,2020-06-01
6,CA-2016-120470,Laila Wilson,Consumer,South,Washington,Technology,Bush Somerset Collection,746.15,8.000000,0.5,7,2020,2020-07-01

## Remove Month and year column that is create by mistake

In [39]:
# Column हटाने के लिए
df.drop(columns=['Month','Year'], inplace=True)

In [40]:
df.head(8)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount,Date
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.300000,2020-01-01
1,CA-2017-129684,Claire Gute,Consumer,South,Seattle,Office Supplies,Apple iPhone 7,240.59,6.000000,0.000000,2020-02-01
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,Technology,Staples Notebook,676.50,5.000000,0.000000,2020-03-01
3,CA-2018-122872,Sara Parker,Home Office,East,Washington,Technology,Hon Deluxe Fabric Chair,511.56,7.000000,0.100000,2020-04-01
4,CA-2018-185789,Sara Parker,Home Office,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.300000,2020-05-01
5,CA-2014-116775,John Lee,Corporate,Central,Seattle,Technology,Fellowes Banks Janalo,511.56,5.709402,0.500000,2020-06-01
6,CA-2016-120470,Laila Wilson,Consumer,South,Washington,Technology,Bush Somerset Collection,746.15,8.000000,0.500000,2020-07-01
7,CA-2017-143684,Darrin Van Huff,Home Office,West,Seattle,Office Supplies,Hon Deluxe Fabric Chair,511.56,9.000000,0.220896,2020-08-01